#!/bin/bash
cp /etc/portage/make.conf /home/tiago/gentoo/etc/portage/make.conf
cp /etc/portage/package.use /home/tiago/gentoo/etc/portage/package.use
cp /etc/portage/savedconfig/x11-wm/dwm-6.2.h /home/tiago/gentoo/etc/portage/savedconfig/x11-wm/dwm-6.2.h

cp /usr/bin/hdmichange /home/tiago/gentoo/usr/bin/hdmichange
cp /usr/bin/gentoobackup /home/tiago/gentoo/usr/bin/gentoobackup
